# ~/.config/starship.toml

# new config
format = """$env_var  $username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$haskell\
$helm\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$vlang\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$sudo\
$jobs\
$battery\
$status\
$container\
$shell\
$fill\
$java\
$terraform\
$cmd_duration\
$python\
$vagrant\
$time\
$line_break\
$character"""

# Inserts a blank line between shell prompts
add_newline = true

# Change command timeout from 500 to 1000 ms
command_timeout = 1000


[env_var.STARSHIP_DISTRO]
format = '[$env_value](white)'
variable = "STARSHIP_DISTRO"
disabled = false

[memory_usage]
disabled = true
threshold = -1

[aws]
style = "bold #ffb86c"

[character]
error_symbol = "[>](bold #ed8796)"
success_symbol = "[>](bold #a6da95)"

[cmd_duration]
style = "bold #f1fa8c"

[directory]
style = "bold #a6da95"
truncation_symbol = "…/"
truncate_to_repo = false


[git_branch]
style = "bold #8aadf4"

[git_status]
style = "bold #f5a97f"

[hostname]
style = "bold #bd93f9"

[username]
format = "[$user]($style) on "
style_user = "bold #8be9fd"

[nodejs]
disabled = true
format = "[$symbol($version )]($style)"

[python]
format = "[$symbol]($style)"

[terraform]
format = "[$symbol $version ]($style)"

[time]
disabled = false
use_12hr = true

[fill]
style = "bold #50FA7B"
symbol = " "

[java]
symbol = " "
format = "[${symbol}(${version} )]($style)"
style = "bold white"

[rust]
symbol = " "

[golang]
symbol = "󰟓 "

[package]
disabled = true

[vagrant]
format = "[$symbol($version )]($style)"
